#!/bin/bash

echo Enter Yahoo Password:
read -s PASS
sendemail -l email.log  -f "kaftra@yahoo.com" \
	-u "THIS IS A TEST EMAIL" \
	-t "epenner@berkeley.edu" \
	-s "smtp.mail.yahoo.com:587" \
	-o tls=yes \
	-xu "kaftra" \
	-xp "$PASS" \
	-o message-file="scratch.py"

echo $?
